# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160911_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='标题'),
        ),
    ]
